#!/usr/bin/env bash
set -euo pipefail

export RVCLAW_HOME="${RVCLAW_HOME:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
export PYTHONPATH="${RVCLAW_HOME}/src:${PYTHONPATH:-}"

export RVCLAW_DATA_DIR="${RVCLAW_DATA_DIR:-/data/rvclaw}"
export RVCLAW_RUNS_DIR="${RVCLAW_RUNS_DIR:-$RVCLAW_DATA_DIR/runs}"
export RVCLAW_LOG_DIR="${RVCLAW_LOG_DIR:-$RVCLAW_DATA_DIR/logs}"

export RVCLAW_PLATFORM_SOC="${RVCLAW_PLATFORM_SOC:-K3-Pico-ITX-32GB}"
export RVCLAW_PLATFORM_ISA="${RVCLAW_PLATFORM_ISA:-rv64gcv}"
export RVCLAW_RVV_VLEN="${RVCLAW_RVV_VLEN:-unknown}"

export LLAMA_CPP_HOME="${LLAMA_CPP_HOME:-$RVCLAW_DATA_DIR/src/spacemit-llama.cpp}"
if [ -d "$LLAMA_CPP_HOME/lib" ]; then
  export LD_LIBRARY_PATH="$LLAMA_CPP_HOME/lib:${LD_LIBRARY_PATH:-}"
fi

export RVCLAW_LLAMA_HOST="${RVCLAW_LLAMA_HOST:-127.0.0.1}"
export RVCLAW_LLAMA_PORT="${RVCLAW_LLAMA_PORT:-9090}"
export RVCLAW_LLAMA_BASE_URL="${RVCLAW_LLAMA_BASE_URL:-http://$RVCLAW_LLAMA_HOST:$RVCLAW_LLAMA_PORT/v1}"
export RVCLAW_LLAMA_MODEL="${RVCLAW_LLAMA_MODEL:-Qwen3-0.6B}"
export RVCLAW_LLAMA_MODEL_PATH="${RVCLAW_LLAMA_MODEL_PATH:-$RVCLAW_DATA_DIR/models/planner-smoke.gguf}"
export RVCLAW_LLAMA_TIMEOUT_S="${RVCLAW_LLAMA_TIMEOUT_S:-120}"
export RVCLAW_LLAMA_THREADS="${RVCLAW_LLAMA_THREADS:-8}"
export RVCLAW_LLAMA_CTX_SIZE="${RVCLAW_LLAMA_CTX_SIZE:-4096}"
export RVCLAW_LLAMA_BATCH_SIZE="${RVCLAW_LLAMA_BATCH_SIZE:-256}"
