#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/env.sh"

mkdir -p "$RVCLAW_LOG_DIR" "$(dirname "$RVCLAW_VISION_SOURCE")"

if [ ! -f "$RVCLAW_VISION_SOURCE" ]; then
  python3 - "$RVCLAW_VISION_SOURCE" <<'PY'
import base64
import sys
from pathlib import Path

png = (
    "iVBORw0KGgoAAAANSUhEUgAAAoAAAAFoCAIAAAC6s0uzAAAGKElEQVR4nO3dQW6kMBRAUQj3v2a2"
    "LKCKUAjZQ43iv+9kq6xZ0qkXAAAAAAB8nG8BAAAA4HcRAQAAAIYRAQAAAIYRAQAAAIYRAQAAAIYR"
    "AQAAAIYRAQAAAIYRAQAAAIYRAQAAAIYRAQAAAIYRAQAAAIYRAQAAAIYRAQAAAIYRAQAAAIYRAQAA"
    "AIYRAQAAAIYRAQAAAIYRAQAAAIYRAQAAAIYRAQAAAIYRAQAAAIZpZ7fb7QIAAADwWJ7n+QIAAADw"
    "mLZtWwAAAACcs23bFgAAAABwzrIsWwAAAACc8zzPFwAAAABwTq/X6wIAAADwWHmeJwAAAAB8jgkA"
    "AAAwjAgAAAAwjAgAAAAwjAgAAAAwjAgAAAAwjAgAAAAwjAgAAAAwjAgAAAAwjAgAAAAwjAgAAAAw"
    "jAgAAAAwjAgAAAAwjAgAAAAwjAgAAAAwjAgAAAAwzVpbWwUAAADgMe+8844AAAAA+P/8+fMBAAAA"
    "wPGiKAgAAADgcaIoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAx"
    "URQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQF"
    "AQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAA"
    "AOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4"
    "TBQFAQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46Io"
    "CgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIA"
    "AAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA"
    "46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA8Jgo"
    "CgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQA"
    "AADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA"
    "8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdE"
    "UhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAxURQF"
    "AAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAA"
    "gMdEUhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAx"
    "URQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQF"
    "AQAAgMdEUhQAAADA46IoCgAAAOAxURQFAAAA8JgoCgIAAAB4TBQFAQAAgMdEUhQAAADA46IoCgAA"
    "AOAxURQFAAAA8JgoCgIAAAB4TH8CR9nkVwq3PAAAAABJRU5ErkJggg=="
)
Path(sys.argv[1]).write_bytes(base64.b64decode(png))
PY
fi

if [ "${RVCLAW_DEVICE_BACKEND:-mock}" = "mock" ]; then
  export RVCLAW_DEVICE_BACKEND="cv_sample"
fi

cd "$RVCLAW_HOME"
python3 -m rvclaw serve \
  --host "$RVCLAW_WEB_HOST" \
  --port "$RVCLAW_WEB_PORT" \
  --planner "${RVCLAW_PLANNER:-llama_cpp}" \
  --runs-dir "$RVCLAW_RUNS_DIR" 2>&1 | tee "$RVCLAW_LOG_DIR/web.log"
